作業目標<br>
在一個陣列中放入多屬性陣列，進一步對陣列做運算<br>
作業重點<br>
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:<br>
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']<br>
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']<br>
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]<br>
rank_list = [8,1,5,4,7,6,2,3]<br>
myopia_list = [True,True,False,False,True,True,False,False]<br>
1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]<br>
2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重


In [4]:
import numpy as np 

In [5]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [6]:
#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
dt= np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'),'formats':('U4','U4',float,int,bool)})
v_array=np.zeros(8,dtype=dt)
v_array['name']=name_list
v_array['sex']=sex_list
v_array['weight']=weight_list
v_array['rank']=rank_list
v_array['myopia']=myopia_list
print(v_array)
print(type(v_array))
print(v_array.shape)
print(v_array.strides)
print(v_array.dtype)

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]
<class 'numpy.ndarray'>
(8,)
(45,)
[('name', '<U4'), ('sex', '<U4'), ('weight', '<f8'), ('rank', '<i4'), ('myopia', '?')]


In [7]:
#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
print(v_array['weight'])
print('weight nanmean=',np.nanmean(v_array['weight']))


[67.5 75.3 50.1 45.5 80.8 90.4 78.4 70.7]
weight nanmean= 69.8375


In [29]:
np.__version__
#wherearray_like of bool, optional ,New in version 1.20.0.

'1.19.2'

In [35]:
#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重
print(v_array['sex'])
print(v_array['sex']=='boy')
print(np.where(v_array['sex']=='boy'),',',type(np.where(v_array['sex']=='boy')))
print(np.where(v_array['sex']=='boy')[0],',',type(np.where(v_array['sex']=='boy')[0]))
print(v_array[np.where(v_array['sex']=='boy')]['weight'])
print(v_array[np.where(v_array['sex']=='boy')[0]]['weight'])
print(v_array[v_array['sex']=='boy'])
print(v_array[v_array['sex']=='boy']['weight'])
print('boys weight nanmean=',np.nanmean(v_array[v_array['sex']=='boy']['weight']))
print('boys weight nanmean=',np.nanmean(v_array['weight'][np.where(v_array['sex']=='boy')]))
print('boys weight nanmean=',np.nanmean(v_array['weight'][np.where(v_array['sex']=='boy')[0]]))


['boy' 'boy' 'girl' 'girl' 'boy' 'boy' 'boy' 'boy']
[ True  True False False  True  True  True  True]
(array([0, 1, 4, 5, 6, 7], dtype=int64),) , <class 'tuple'>
[0 1 4 5 6 7] , <class 'numpy.ndarray'>
[67.5 75.3 80.8 90.4 78.4 70.7]
[67.5 75.3 80.8 90.4 78.4 70.7]
[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]
[67.5 75.3 80.8 90.4 78.4 70.7]
boys weight nanmean= 77.18333333333332
boys weight nanmean= 77.18333333333332
boys weight nanmean= 77.18333333333332


In [19]:
#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重
print(v_array['sex'])
print(v_array['sex']=='girl')
print(v_array[v_array['sex']=='girl'])
print(v_array[v_array['sex']=='girl']['weight'])
print('girls weight nanmean=',np.nanmean(v_array[v_array['sex']=='girl']['weight']))

['boy' 'boy' 'girl' 'girl' 'boy' 'boy' 'boy' 'boy']
[False False  True  True False False False False]
[('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)]
[50.1 45.5]
boys weight nanmean= 47.8
