# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [19]:
# 記得先 Import 正確的套件
import numpy as np

#%timeit -n 2 -r 1 a=2;print("a=",a);a=a+1;print("b=",a);

In [3]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [4]:
Z

array([[[0, 7, 1, ..., 2, 0, 7],
        [6, 6, 3, ..., 9, 9, 7],
        [3, 3, 5, ..., 2, 6, 5],
        ...,
        [3, 2, 1, ..., 6, 8, 9],
        [0, 9, 8, ..., 2, 0, 1],
        [5, 5, 6, ..., 6, 0, 9]],

       [[5, 5, 8, ..., 3, 8, 9],
        [2, 3, 4, ..., 9, 1, 8],
        [5, 0, 4, ..., 9, 8, 3],
        ...,
        [4, 1, 3, ..., 5, 1, 0],
        [1, 0, 1, ..., 7, 0, 4],
        [5, 8, 7, ..., 0, 9, 4]],

       [[0, 8, 9, ..., 8, 3, 3],
        [3, 1, 8, ..., 5, 9, 0],
        [7, 5, 8, ..., 7, 3, 0],
        ...,
        [9, 6, 8, ..., 3, 8, 1],
        [3, 1, 8, ..., 3, 0, 7],
        [9, 8, 9, ..., 8, 7, 9]],

       ...,

       [[1, 1, 1, ..., 6, 0, 8],
        [2, 3, 7, ..., 4, 9, 8],
        [9, 1, 2, ..., 6, 2, 7],
        ...,
        [5, 6, 2, ..., 5, 4, 0],
        [6, 9, 5, ..., 0, 5, 2],
        [5, 3, 5, ..., 9, 0, 0]],

       [[1, 4, 2, ..., 3, 0, 1],
        [5, 6, 2, ..., 1, 2, 6],
        [4, 2, 5, ..., 4, 4, 6],
        ...,
        [7, 8, 6, ..., 

In [6]:
#方法1:矩陣加1
%timeit -n 10 b=Z+1
#print(b)

1.52 ms ± 151 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
#方法2:矩陣相加
%timeit -n 10 a=np.ones((100, 100, 100));b=Z+a;
#print(b)

5.04 ms ± 367 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
#方法3:flat
%timeit -n 10 for d in Z.flat:  d=d+1;

308 ms ± 3.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
#方法4:for loop
%timeit -n 10 [a2+1 for a0 in Z for a1 in a0 for a2 in a1]

399 ms ± 12.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
#方法5:nditer
%timeit -n 10 for d in np.nditer(Z): d=d+1;

1.01 s ± 25.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [35]:
Z = np.random.randint(0,10,50)
print(Z)

[6 2 9 4 5 4 3 9 2 4 3 8 0 3 4 1 8 2 1 7 5 2 6 0 4 8 0 1 2 9 1 7 2 5 3 8 3
 6 7 2 3 7 6 2 4 0 0 5 3 3]


In [36]:
#眾數:
counts = np.bincount(Z)  #傳回數字累計
print(counts) 
maxCount=np.max(counts) #傳回最大累計值
print(maxCount)
v_modes=np.where(counts==maxCount)
print(v_modes)
for v_mode in v_modes[0]:
  print("出現頻率最高的數值=",v_mode)
  print("  位置在=",np.where(Z==v_mode))

[5 4 8 8 6 4 4 4 4 3]
8
(array([2, 3], dtype=int64),)
出現頻率最高的數值= 2
  位置在= (array([ 1,  8, 17, 21, 28, 32, 39, 43], dtype=int64),)
出現頻率最高的數值= 3
  位置在= (array([ 6, 10, 13, 34, 36, 40, 48, 49], dtype=int64),)


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [40]:
a = np.random.randint(10, size=6) 
print(a)
print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.tolist())
print(list(c))


[1 3 8 8 4 0]
[1, 3, 8, 8, 4, 0]
[1, 3, 8, 8, 4, 0]
[[8 2 0 1]
 [1 1 7 5]
 [6 1 0 7]]
[[8, 2, 0, 1], [1, 1, 7, 5], [6, 1, 0, 7]]
[array([8, 2, 0, 1]), array([1, 1, 7, 5]), array([6, 1, 0, 7])]
[[[8 6]
  [6 3]
  [9 8]]

 [[7 9]
  [6 8]
  [8 6]]]
[[[8, 6], [6, 3], [9, 8]], [[7, 9], [6, 8], [8, 6]]]
[array([[8, 6],
       [6, 3],
       [9, 8]]), array([[7, 9],
       [6, 8],
       [8, 6]])]


In [74]:
def funList(var):
  #print(type(var))
  if type(var) == np.ndarray:
    a1 = var.shape  
    #print(a1,",",len(a1))
    if len(a1) == 1:
      #print("v1",list(var))
      return list(var)
    else:
      #print("v2",list(var))
      a2 = list(var)
      a4 = [funList(a3) for a3 in a2]
      #print(a4)
      return a4
  else:
    return var


print(funList(10))
print("a.tolist()=",a.tolist())
print(funList(a))
print("b.tolist()=",b.tolist())
print(funList(b))
print("c.tolist()=",c.tolist())
print(funList(c))
  
    



10
a.tolist()= [7, 8, 2, 5, 2, 9]
[7, 8, 2, 5, 2, 9]
b.tolist()= [[6, 7, 4, 1], [1, 4, 7, 0], [1, 7, 2, 3]]
[[6, 7, 4, 1], [1, 4, 7, 0], [1, 7, 2, 3]]
c.tolist()= [[[7, 7], [2, 5], [6, 6]], [[4, 1], [4, 4], [5, 7]]]
[[[7, 7], [2, 5], [6, 6]], [[4, 1], [4, 4], [5, 7]]]
